package game

const (
	SCREEN_WIDTH  = 800
	SCREEN_HEIGHT = 500

	WINDOW_WIDTH  = 800
	WINDOW_HEIGHT = 500

	CELL_WIDTH  = 10
	CELL_HEIGHT = 10

	GRID_WIDTH  = SCREEN_WIDTH / CELL_WIDTH
	GRID_HEIGHT = SCREEN_HEIGHT / CELL_HEIGHT
)
