package game

const (
	SCREEN_WIDTH  = 500
	SCREEN_HEIGHT = 400

	WINDOW_WIDTH  = 500
	WINDOW_HEIGHT = 400

	CELL_WIDTH  = 10
	CELL_HEIGHT = 10

	GRID_WIDTH  = SCREEN_WIDTH / CELL_WIDTH
	GRID_HEIGHT = SCREEN_HEIGHT / CELL_HEIGHT
)
